(function(){'use strict';
var WORDS=/^(screen|screens|display|displays|billboard|billboards|poster|posters|sign|signs|signage|advert|advertisement|advertising|ad|ads|promo|promotion|project|projects|monitor|monitors|television|tv|marquee|logo|logos|brand|branding|graphic|graphics|artwork|video|videos|media|panel|panels|kiosk|terminal|lightbox)$/i;
var KNOWN=/(samsy|smsy|nintendo|notnyc|jiometry)/i;
var STRUCTURAL=/(wall|walls|floor|floors|ground|road|street|roof|ceiling|glass|window|windows|facade|building|concrete|brick|metal|frame|beam|column|rail|railing|pipe|pipes|duct|stairs|stair|door|doors|sidewalk|curb|terrain|neon|light|lights|lamp|lamps|trim|border|collision|shadow|sky|water)/i;
var LABELS=['SEELARY','CAMPAIGN','CREATE','LAUNCH','GROW','MOTION','PRODUCT','MEDIA','BRAND','STORY','BUILD','SCALE','CONNECT','PERFORM','REACH','CONVERT'];
var SUB=['CREATIVE • MEDIA • GROWTH','CAMPAIGN IN MOTION','MAKE ATTENTION MOVE','PRODUCT • STORY • ACTION','FROM IDEA TO IMPACT','DESIGNED TO BE SEEN'];
var PALETTES=[['#05060a','#ff4d8d','#7c5cff','#35e0c1'],['#080809','#ff8a34','#ef3cff','#55d8ff'],['#04080a','#2fe4a7','#2c8cff','#d4ff44'],['#090609','#ff335f','#9d5cff','#ffd166'],['#04070d','#46d7ff','#365cff','#ff5cc8'],['#0a0704','#ffc247','#ff5d52','#9d6bff']];
var diag=window.__seelaryStaticReplacement={active:true,status:'waiting',mode:'all-display-content-only-v5',coverage:'named-content + flat-emissive/unlit textured display planes',transport:'fetch-cyberfix-only',geometryModified:false,animationModified:false,materialBehaviorPreserved:true,matchedMeshes:0,matchedNodes:0,matchedMaterials:0,namedMatchedPrimitives:0,heuristicMatchedPrimitives:0,excludedStructural:0,replacedPrimitives:0,clonedMaterials:0,replacementTextures:0,skippedUntextured:0,samples:[],fallback:'original-glb'};
window.__seelaryBuildingContent=Object.assign(window.__seelaryBuildingContent||{},{staticMode:'all-display-content-only-v5',staticDesignPreserved:true,staticGeometryPreserved:true,staticAnimationPreserved:true,interiorExteriorCoverage:true,displayHeuristic:'flat-simple-textured-emissive-or-unlit'});
function clean(s){return String(s||'').toLowerCase().replace(/([a-z])([0-9])/g,'$1_$2').replace(/([0-9])([a-z])/g,'$1_$2')}
function contentName(s){s=clean(s);if(!s)return false;if(KNOWN.test(s))return true;var parts=s.split(/[^a-z0-9]+/).filter(Boolean);for(var i=0;i<parts.length;i++)if(WORDS.test(parts[i]))return true;return /^(screen|display|billboard|poster|sign|advert|promo|project|monitor|tv|logo|video|media|panel|kiosk|terminal|lightbox)\d*$/.test(s.replace(/[^a-z0-9]/g,''))}
function structuralName(s){s=clean(s);return !!s&&STRUCTURAL.test(s)&&!contentName(s)}
function clone(v){return JSON.parse(JSON.stringify(v))}
function bytes(blob){return blob.arrayBuffer().then(function(b){return new Uint8Array(b)})}
function readGLB(buf){var d=new DataView(buf);if(buf.byteLength<20||d.getUint32(0,true)!==0x46546c67||d.getUint32(4,true)!==2)throw new Error('not-glb2');var total=Math.min(d.getUint32(8,true),buf.byteLength),o=12,json=null,bin=null;while(o+8<=total){var len=d.getUint32(o,true),type=d.getUint32(o+4,true),start=o+8,end=start+len;if(end>total)throw new Error('bad-glb-chunk');var data=new Uint8Array(buf,start,len);if(type===0x4e4f534a)json=JSON.parse(new TextDecoder().decode(data).replace(/\0+$/,'').trim());if(type===0x004e4942)bin=new Uint8Array(data);o=end}if(!json||!bin)throw new Error('missing-glb-chunk');return{json:json,bin:bin}}
function imageIndexForTexture(j,ti){var t=(j.textures||[])[ti];if(!t)return-1;if(Number.isInteger(t.source))return t.source;var e=t.extensions||{},x=e.KHR_texture_basisu||e.EXT_texture_webp||e.MSFT_texture_dds;return x&&Number.isInteger(x.source)?x.source:-1}
function imageBytes(j,bin,ii){var im=(j.images||[])[ii],bv=im&&Number.isInteger(im.bufferView)&&(j.bufferViews||[])[im.bufferView];if(!bv||bv.buffer!==0)return null;var o=bv.byteOffset||0,l=bv.byteLength||0;if(o<0||l<=0||o+l>bin.length)return null;return bin.subarray(o,o+l)}
function dims(data){try{if(!data||data.length<24)return null;if(data[0]===137&&data[1]===80&&data[2]===78&&data[3]===71){var dv=new DataView(data.buffer,data.byteOffset,data.byteLength);return{w:dv.getUint32(16,false),h:dv.getUint32(20,false)}}if(data[0]===255&&data[1]===216){var p=2;while(p+9<data.length){if(data[p]!==255){p++;continue}var m=data[p+1],len=(data[p+2]<<8)|data[p+3];if((m>=192&&m<=195)||(m>=197&&m<=199)||(m>=201&&m<=203)||(m>=205&&m<=207))return{h:(data[p+5]<<8)|data[p+6],w:(data[p+7]<<8)|data[p+8]};if(len<2)break;p+=2+len}}}catch(e){}return null}
function art(label,index,d){d=d||{};var ar=d.w&&d.h?d.w/d.h:2,w=1024,h=Math.max(256,Math.min(1024,Math.round(w/Math.max(.5,Math.min(4,ar))))),c=document.createElement('canvas');c.width=w;c.height=h;var g=c.getContext('2d'),p=PALETTES[index%PALETTES.length],gr=g.createLinearGradient(0,0,w,h);gr.addColorStop(0,p[0]);gr.addColorStop(.58,p[0]);gr.addColorStop(1,p[2]);g.fillStyle=gr;g.fillRect(0,0,w,h);var mode=index%4;g.save();g.globalAlpha=.22;if(mode===0){for(var k=0;k<9;k++){g.fillStyle=k%2?p[1]:p[3];g.beginPath();g.arc(w*(.67+.24*Math.cos(k*1.27)),h*(.5+.35*Math.sin(k*1.61)),Math.max(18,h*(.06+k*.01)),0,Math.PI*2);g.fill()}}else if(mode===1){for(var r=0;r<5;r++){g.fillStyle=r%2?p[3]:p[1];g.fillRect(w*(.56+r*.055),h*.17,w*.035,h*(.55-r*.06))}}else if(mode===2){g.translate(w*.72,h*.46);g.rotate(-.2);for(var q=0;q<6;q++){g.strokeStyle=q%2?p[1]:p[3];g.lineWidth=Math.max(5,h*.015);g.strokeRect(-w*(.18+q*.018),-h*(.22+q*.014),w*(.36+q*.036),h*(.44+q*.028))}}else{for(var a=0;a<7;a++){g.fillStyle=a%2?p[1]:p[3];g.beginPath();g.moveTo(w*.55,h*(.18+a*.09));g.lineTo(w*.94,h*(.1+a*.12));g.lineTo(w*.88,h*(.18+a*.11));g.closePath();g.fill()}}g.restore();g.fillStyle='#fff';g.font='800 '+Math.max(20,Math.round(h*.075))+'px Arial,Helvetica,sans-serif';g.fillText('SEELARY',w*.055,h*.13);var word=LABELS[index%LABELS.length];g.font='900 '+Math.max(42,Math.round(h*.23))+'px Arial,Helvetica,sans-serif';g.fillText(word,w*.052,h*.58);g.font='700 '+Math.max(14,Math.round(h*.052))+'px Arial,Helvetica,sans-serif';g.globalAlpha=.72;g.fillText(SUB[index%SUB.length],w*.055,h*.73);g.globalAlpha=1;g.fillStyle=p[3];g.fillRect(w*.055,h*.82,w*(.22+.055*(index%8)),Math.max(5,h*.018));g.fillStyle='rgba(255,255,255,.16)';g.fillRect(w*.055,h*.9,w*.61,Math.max(1,h*.004));return new Promise(function(resolve,reject){c.toBlob(function(b){b?bytes(b).then(resolve,reject):reject(new Error('panel-png-failed'))},'image/png')})}
function textureSlots(mat){var out=[];if(mat&&mat.pbrMetallicRoughness&&mat.pbrMetallicRoughness.baseColorTexture)out.push(['pbrMetallicRoughness','baseColorTexture']);if(mat&&mat.emissiveTexture)out.push(['emissiveTexture']);return out}
function getInfo(mat,path){return path.length===2?mat[path[0]]&&mat[path[0]][path[1]]:mat[path[0]]}
function setInfo(mat,path,val){if(path.length===2){mat[path[0]]=mat[path[0]]||{};mat[path[0]][path[1]]=val}else mat[path[0]]=val}
function materialNames(j,mat){var names=[mat&&mat.name||''];textureSlots(mat).forEach(function(path){var info=getInfo(mat,path),ii=info&&imageIndexForTexture(j,info.index),im=ii>=0&&(j.images||[])[ii];if(im&&im.name)names.push(im.name)});return names.join(' ')}
function emissiveLike(mat){if(!mat)return false;if(mat.emissiveTexture)return true;var e=mat.emissiveFactor;if(e&&((+e[0]||0)+(+e[1]||0)+(+e[2]||0)>.04))return true;if(mat.extensions&&mat.extensions.KHR_materials_unlit)return true;return false}
function primitiveBounds(j,pr){var ai=pr&&pr.attributes&&pr.attributes.POSITION,a=Number.isInteger(ai)&&(j.accessors||[])[ai];if(!a)return null;var out={count:a.count||0,indexCount:0,dims:null};if(Number.isInteger(pr.indices)){var ia=(j.accessors||[])[pr.indices];out.indexCount=ia&&ia.count||0}if(a.min&&a.max&&a.min.length>=3&&a.max.length>=3){out.dims=[Math.abs(a.max[0]-a.min[0]),Math.abs(a.max[1]-a.min[1]),Math.abs(a.max[2]-a.min[2])].sort(function(x,y){return x-y})}return out}
function displayPlane(j,pr,mat,names){if(!pr||!mat||structuralName(names))return false;if(!pr.attributes||!Number.isInteger(pr.attributes.TEXCOORD_0))return false;if(!textureSlots(mat).length||!emissiveLike(mat))return false;var b=primitiveBounds(j,pr);if(!b)return false;var simple=(b.count>0&&b.count<=64)&&(b.indexCount===0||b.indexCount<=192);if(!simple)return false;if(b.dims){var a=b.dims[0],m=b.dims[1],z=b.dims[2];if(z<=0||m<=0)return false;var flat=a<=Math.max(.02,m*.045),ratio=z/m;if(!flat||ratio>10)return false;return true}return b.count<=12}
function addSample(kind,name){if(diag.samples.length<50)diag.samples.push({kind:kind,name:String(name||'unnamed')})}
function rebuild(parsed){var j=parsed.json,bin=parsed.bin,meshes=j.meshes||[],nodes=j.nodes||[],materials=j.materials||[],textures=j.textures||(j.textures=[]),images=j.images||(j.images=[]),views=j.bufferViews||(j.bufferViews=[]);var materialTargets=new Set(),meshTargets=new Set(),nodeTargets=[];
materials.forEach(function(m,mi){var names=materialNames(j,m);if(contentName(names)){materialTargets.add(mi);diag.matchedMaterials++}});
meshes.forEach(function(m,mi){if(contentName(m&&m.name)){meshTargets.add(mi);diag.matchedMeshes++}});
nodes.forEach(function(n,ni){if(Number.isInteger(n&&n.mesh)&&contentName(n.name||'')){nodeTargets.push(ni);diag.matchedNodes++}});
var tasks=[],serial=0;
function cloneMaterial(mi,label){var old=materials[mi];if(!old)return Promise.resolve(mi);var nm=clone(old),slots=textureSlots(old),valid=[];slots.forEach(function(path){var info=getInfo(old,path);if(info&&Number.isInteger(info.index))valid.push({path:path,info:info,textureIndex:info.index})});if(!valid.length){diag.skippedUntextured++;return Promise.resolve(mi)}var first=valid[0],ii=imageIndexForTexture(j,first.textureIndex),im=ii>=0&&images[ii],ib=ii>=0&&imageBytes(j,bin,ii),dm=dims(ib),idx=serial++;return art(label,idx,dm).then(function(png){valid.forEach(function(v){var oldTex=textures[v.textureIndex];if(!oldTex)return;var asset={png:png,oldTex:oldTex,label:label,idx:idx};tasks.push(asset);var info=clone(v.info);info.__seelaryAsset=asset;setInfo(nm,v.path,info)});var nmi=materials.length;materials.push(nm);diag.clonedMaterials++;return{index:nmi,material:nm}})}
var ops=[];
meshes.forEach(function(m,mi){(m.primitives||[]).forEach(function(pr,pi){if(!Number.isInteger(pr.material))return;var mat=materials[pr.material],names=[m&&m.name||'',materialNames(j,mat)].join(' '),named=meshTargets.has(mi)||materialTargets.has(pr.material),heuristic=!named&&displayPlane(j,pr,mat,names);if(!named&&!heuristic){if(structuralName(names))diag.excludedStructural++;return}if(named){diag.namedMatchedPrimitives++;addSample('named',m&&m.name||mat&&mat.name)}else{diag.heuristicMatchedPrimitives++;addSample('flat-display',m&&m.name||mat&&mat.name)}ops.push(cloneMaterial(pr.material,(m.name||mat&&mat.name||'surface')+'_'+pi).then(function(r){if(typeof r==='object'){pr.material=r.index;diag.replacedPrimitives++}}))})});
nodeTargets.forEach(function(ni){var n=nodes[ni],oldMesh=meshes[n.mesh];if(!oldMesh||meshTargets.has(n.mesh))return;var cm=clone(oldMesh),mi=meshes.length;meshes.push(cm);n.mesh=mi;(cm.primitives||[]).forEach(function(pr,pi){if(!Number.isInteger(pr.material))return;diag.namedMatchedPrimitives++;addSample('named-node',n.name);ops.push(cloneMaterial(pr.material,(n.name||'node')+'_'+pi).then(function(r){if(typeof r==='object'){pr.material=r.index;diag.replacedPrimitives++}}))})});
if(!ops.length){diag.status='no-display-surfaces-found-original-preserved';return Promise.resolve(null)}
return Promise.all(ops).then(function(){var pieces=[bin],cursor=bin.length,assetToTexture=new Map();function append(data,name){var pad=(4-(cursor%4))%4;if(pad){pieces.push(new Uint8Array(pad));cursor+=pad}var bv=views.length;views.push({buffer:0,byteOffset:cursor,byteLength:data.length,name:name+'Buffer'});pieces.push(data);cursor+=data.length;return bv}tasks.forEach(function(a){if(assetToTexture.has(a))return;var bv=append(a.png,'SeelaryContent'+a.idx),ii=images.length;images.push({bufferView:bv,mimeType:'image/png',name:'SeelaryStockAdImage'+a.idx});var nt=clone(a.oldTex);nt.source=ii;if(nt.extensions){nt.extensions=clone(nt.extensions);delete nt.extensions.KHR_texture_basisu;delete nt.extensions.EXT_texture_webp;delete nt.extensions.MSFT_texture_dds;if(!Object.keys(nt.extensions).length)delete nt.extensions}nt.name='SeelaryStockAdTexture'+a.idx;var ti=textures.length;textures.push(nt);assetToTexture.set(a,ti);diag.replacementTextures++});materials.forEach(function(m){textureSlots(m).forEach(function(path){var info=getInfo(m,path);if(info&&info.__seelaryAsset){var a=info.__seelaryAsset;delete info.__seelaryAsset;info.index=assetToTexture.get(a)}})});var newBin=new Uint8Array(cursor),pos=0;pieces.forEach(function(x){newBin.set(x,pos);pos+=x.length});if(j.buffers&&j.buffers[0])j.buffers[0].byteLength=newBin.length;diag.status='all-display-stock-ads-replaced';var enc=new TextEncoder().encode(JSON.stringify(j)),jp=(enc.length+3)&~3,bp=(newBin.length+3)&~3,total=12+8+jp+8+bp,out=new Uint8Array(total),d=new DataView(out.buffer);d.setUint32(0,0x46546c67,true);d.setUint32(4,2,true);d.setUint32(8,total,true);d.setUint32(12,jp,true);d.setUint32(16,0x4e4f534a,true);out.set(enc,20);for(var q=20+enc.length;q<20+jp;q++)out[q]=32;var bo=20+jp;d.setUint32(bo,bp,true);d.setUint32(bo+4,0x004e4942,true);out.set(newBin,bo+8);return out.buffer})}
var nativeFetch=window.fetch&&window.fetch.bind(window);if(nativeFetch)window.fetch=function(input,init){var path='';try{path=new URL(typeof input==='string'?input:(input&&input.url)||'',location.href).pathname}catch(e){}if(!/\/models\/cyberfix\.glb$/i.test(path))return nativeFetch(input,init);return nativeFetch(input,init).then(function(r){if(!r.ok)return r;return r.arrayBuffer().then(function(original){diag.status='processing';return rebuild(readGLB(original)).then(function(changed){if(!changed)return new Response(original,{status:r.status,statusText:r.statusText,headers:r.headers});return new Response(changed,{status:r.status,statusText:r.statusText,headers:r.headers})}).catch(function(e){diag.status='rewrite-failed-original-preserved';diag.error=String(e);return new Response(original,{status:r.status,statusText:r.statusText,headers:r.headers})})})})};
})();