(function(){'use strict';
var WORDS=/^(screen|screens|display|displays|billboard|billboards|poster|posters|sign|signs|signage|advert|advertisement|advertising|ad|ads|promo|promotion|project|projects|monitor|monitors|television|tv|marquee|logo|logos|brand|branding|graphic|graphics|artwork|video|videos|media)$/i;
var KNOWN=/(samsy|smsy|nintendo|notnyc|jiometry)/i;
var LABELS=['SEELARY','CAMPAIGN','CREATE','LAUNCH','GROW','MOTION','PRODUCT','MEDIA','BRAND','STORY','BUILD','SCALE'];
var PALETTES=[['#05060a','#ff4d8d','#7c5cff','#35e0c1'],['#080809','#ff8a34','#ef3cff','#55d8ff'],['#04080a','#2fe4a7','#2c8cff','#d4ff44'],['#090609','#ff335f','#9d5cff','#ffd166']];
var diag=window.__seelaryStaticReplacement={active:true,status:'waiting',mode:'content-only-texture-substitution',transport:'fetch-cyberfix-only',geometryModified:false,animationModified:false,materialBehaviorPreserved:true,matchedMeshes:0,matchedNodes:0,matchedMaterials:0,replacedPrimitives:0,clonedMaterials:0,replacementTextures:0,skippedUntextured:0,fallback:'original-glb'};
window.__seelaryBuildingContent=Object.assign(window.__seelaryBuildingContent||{},{staticMode:'content-only-texture-substitution',staticDesignPreserved:true,staticGeometryPreserved:true,staticAnimationPreserved:true});
function clean(s){return String(s||'').toLowerCase().replace(/([a-z])([0-9])/g,'$1_$2').replace(/([0-9])([a-z])/g,'$1_$2')}
function contentName(s){s=clean(s);if(!s)return false;if(KNOWN.test(s))return true;var parts=s.split(/[^a-z0-9]+/).filter(Boolean);for(var i=0;i<parts.length;i++)if(WORDS.test(parts[i]))return true;return /^(screen|display|billboard|poster|sign|advert|promo|project|monitor|tv|logo|video|media)\d*$/.test(s.replace(/[^a-z0-9]/g,''))}
function clone(v){return JSON.parse(JSON.stringify(v))}
function bytes(blob){return blob.arrayBuffer().then(function(b){return new Uint8Array(b)})}
function readGLB(buf){var d=new DataView(buf);if(buf.byteLength<20||d.getUint32(0,true)!==0x46546c67||d.getUint32(4,true)!==2)throw new Error('not-glb2');var total=Math.min(d.getUint32(8,true),buf.byteLength),o=12,json=null,bin=null;while(o+8<=total){var len=d.getUint32(o,true),type=d.getUint32(o+4,true),start=o+8,end=start+len;if(end>total)throw new Error('bad-glb-chunk');var data=new Uint8Array(buf,start,len);if(type===0x4e4f534a)json=JSON.parse(new TextDecoder().decode(data).replace(/\0+$/,'').trim());if(type===0x004e4942)bin=new Uint8Array(data);o=end}if(!json||!bin)throw new Error('missing-glb-chunk');return{json:json,bin:bin}}
function imageIndexForTexture(j,ti){var t=(j.textures||[])[ti];if(!t)return-1;if(Number.isInteger(t.source))return t.source;var e=t.extensions&&t.extensions.KHR_texture_basisu;return e&&Number.isInteger(e.source)?e.source:-1}
function imageBytes(j,bin,ii){var im=(j.images||[])[ii],bv=im&&Number.isInteger(im.bufferView)&&(j.bufferViews||[])[im.bufferView];if(!bv||bv.buffer!==0)return null;var o=bv.byteOffset||0,l=bv.byteLength||0;if(o<0||l<=0||o+l>bin.length)return null;return bin.subarray(o,o+l)}
function dims(data,mime){try{if(!data||data.length<24)return null;if(data[0]===137&&data[1]===80&&data[2]===78&&data[3]===71){var dv=new DataView(data.buffer,data.byteOffset,data.byteLength);return{w:dv.getUint32(16,false),h:dv.getUint32(20,false)}}if(data[0]===255&&data[1]===216){var p=2;while(p+9<data.length){if(data[p]!==255){p++;continue}var m=data[p+1],len=(data[p+2]<<8)|data[p+3];if((m>=192&&m<=195)||(m>=197&&m<=199)||(m>=201&&m<=203)||(m>=205&&m<=207))return{h:(data[p+5]<<8)|data[p+6],w:(data[p+7]<<8)|data[p+8]};if(len<2)break;p+=2+len}}}catch(e){}return null}
function art(label,index,d){d=d||{};var ar=d.w&&d.h?d.w/d.h:2,w=1024,h=Math.max(256,Math.min(1024,Math.round(w/Math.max(.5,Math.min(4,ar))))),c=document.createElement('canvas');c.width=w;c.height=h;var g=c.getContext('2d'),p=PALETTES[index%PALETTES.length],gr=g.createLinearGradient(0,0,w,h);gr.addColorStop(0,p[0]);gr.addColorStop(.62,p[0]);gr.addColorStop(1,p[2]);g.fillStyle=gr;g.fillRect(0,0,w,h);g.globalAlpha=.18;for(var k=0;k<8;k++){g.fillStyle=k%2?p[1]:p[3];g.beginPath();g.arc(w*(.68+.22*Math.cos(k*1.31)),h*(.48+.34*Math.sin(k*1.67)),Math.max(18,h*(.07+k*.012)),0,Math.PI*2);g.fill()}g.globalAlpha=1;g.fillStyle='#fff';g.font='800 '+Math.max(20,Math.round(h*.075))+'px Arial,Helvetica,sans-serif';g.fillText('SEELARY',w*.055,h*.13);var word=LABELS[index%LABELS.length];g.font='900 '+Math.max(42,Math.round(h*.23))+'px Arial,Helvetica,sans-serif';g.fillText(word,w*.052,h*.58);g.font='700 '+Math.max(14,Math.round(h*.052))+'px Arial,Helvetica,sans-serif';g.globalAlpha=.7;g.fillText('CREATIVE • MEDIA • GROWTH',w*.055,h*.73);g.globalAlpha=1;g.fillStyle=p[3];g.fillRect(w*.055,h*.82,w*(.22+.07*(index%6)),Math.max(5,h*.018));g.fillStyle='rgba(255,255,255,.16)';g.fillRect(w*.055,h*.9,w*.61,Math.max(1,h*.004));return new Promise(function(resolve,reject){c.toBlob(function(b){b?bytes(b).then(resolve,reject):reject(new Error('panel-png-failed'))},'image/png')})}
function textureSlots(mat){var out=[];if(mat&&mat.pbrMetallicRoughness&&mat.pbrMetallicRoughness.baseColorTexture)out.push(['pbrMetallicRoughness','baseColorTexture']);if(mat&&mat.emissiveTexture)out.push(['emissiveTexture']);return out}
function getInfo(mat,path){return path.length===2?mat[path[0]]&&mat[path[0]][path[1]]:mat[path[0]]}
function setInfo(mat,path,val){if(path.length===2){mat[path[0]]=mat[path[0]]||{};mat[path[0]][path[1]]=val}else mat[path[0]]=val}
function rebuild(parsed){var j=parsed.json,bin=parsed.bin,meshes=j.meshes||[],nodes=j.nodes||[],materials=j.materials||[],textures=j.textures||(j.textures=[]),images=j.images||(j.images=[]),views=j.bufferViews||(j.bufferViews=[]);var materialTargets=new Set(),meshTargets=new Set(),nodeTargets=[];
materials.forEach(function(m,mi){var names=[m&&m.name||''];textureSlots(m).forEach(function(path){var info=getInfo(m,path),ii=info&&imageIndexForTexture(j,info.index),im=ii>=0&&images[ii];if(im&&im.name)names.push(im.name)});if(contentName(names.join(' '))){materialTargets.add(mi);diag.matchedMaterials++}});
meshes.forEach(function(m,mi){if(contentName(m&&m.name)){meshTargets.add(mi);diag.matchedMeshes++}});
nodes.forEach(function(n,ni){if(Number.isInteger(n&&n.mesh)&&contentName(n.name||'')){nodeTargets.push(ni);diag.matchedNodes++}});
if(!materialTargets.size&&!meshTargets.size&&!nodeTargets.length){diag.status='no-content-surfaces-found-original-preserved';return Promise.resolve(null)}
var tasks=[],serial=0;
function cloneMaterial(mi,label){var old=materials[mi];if(!old)return Promise.resolve(mi);var nm=clone(old),slots=textureSlots(old),valid=[];slots.forEach(function(path){var info=getInfo(old,path);if(info&&Number.isInteger(info.index))valid.push({path:path,info:info,textureIndex:info.index})});if(!valid.length){diag.skippedUntextured++;return Promise.resolve(mi)}var first=valid[0],ii=imageIndexForTexture(j,first.textureIndex),im=ii>=0&&images[ii],ib=ii>=0&&imageBytes(j,bin,ii),dm=dims(ib,im&&im.mimeType),idx=serial++;return art(label,idx,dm).then(function(png){valid.forEach(function(v){var oldTex=textures[v.textureIndex];if(!oldTex)return;var asset={png:png,oldTex:oldTex,label:label,idx:idx};tasks.push(asset);var info=clone(v.info);info.__seelaryAsset=asset;setInfo(nm,v.path,info)});var nmi=materials.length;materials.push(nm);diag.clonedMaterials++;return{index:nmi,material:nm}})}
var ops=[];
meshes.forEach(function(m,mi){(m.primitives||[]).forEach(function(pr,pi){if(!Number.isInteger(pr.material))return;if(meshTargets.has(mi)||materialTargets.has(pr.material)){ops.push(cloneMaterial(pr.material,(m.name||'surface')+'_'+pi).then(function(r){if(typeof r==='object'){pr.material=r.index;diag.replacedPrimitives++}}))}})});
nodeTargets.forEach(function(ni){var n=nodes[ni],oldMesh=meshes[n.mesh];if(!oldMesh||meshTargets.has(n.mesh))return;var cm=clone(oldMesh),mi=meshes.length;meshes.push(cm);n.mesh=mi;(cm.primitives||[]).forEach(function(pr,pi){if(!Number.isInteger(pr.material))return;ops.push(cloneMaterial(pr.material,(n.name||'node')+'_'+pi).then(function(r){if(typeof r==='object'){pr.material=r.index;diag.replacedPrimitives++}}))})});
return Promise.all(ops).then(function(){var pieces=[bin],cursor=bin.length,assetToTexture=new Map();function append(bytes,name){var pad=(4-(cursor%4))%4;if(pad){pieces.push(new Uint8Array(pad));cursor+=pad}var bv=views.length;views.push({buffer:0,byteOffset:cursor,byteLength:bytes.length,name:name+'Buffer'});pieces.push(bytes);cursor+=bytes.length;return bv}tasks.forEach(function(a){if(assetToTexture.has(a))return;var bv=append(a.png,'SeelaryContent'+a.idx),ii=images.length;images.push({bufferView:bv,mimeType:'image/png',name:'SeelaryContentImage'+a.idx});var nt=clone(a.oldTex);nt.source=ii;if(nt.extensions&&nt.extensions.KHR_texture_basisu){nt.extensions=clone(nt.extensions);delete nt.extensions.KHR_texture_basisu;if(!Object.keys(nt.extensions).length)delete nt.extensions}nt.name='SeelaryContentTexture'+a.idx;var ti=textures.length;textures.push(nt);assetToTexture.set(a,ti);diag.replacementTextures++});materials.slice(0).forEach(function(m){textureSlots(m).forEach(function(path){var info=getInfo(m,path);if(info&&info.__seelaryAsset){var a=info.__seelaryAsset;delete info.__seelaryAsset;info.index=assetToTexture.get(a)}})});var newBin=new Uint8Array(cursor),pos=0;pieces.forEach(function(x){newBin.set(x,pos);pos+=x.length});if(j.buffers&&j.buffers[0])j.buffers[0].byteLength=newBin.length;diag.status='content-surfaces-replaced';var enc=new TextEncoder().encode(JSON.stringify(j)),jp=(enc.length+3)&~3,bp=(newBin.length+3)&~3,total=12+8+jp+8+bp,out=new Uint8Array(total),d=new DataView(out.buffer);d.setUint32(0,0x46546c67,true);d.setUint32(4,2,true);d.setUint32(8,total,true);d.setUint32(12,jp,true);d.setUint32(16,0x4e4f534a,true);out.set(enc,20);for(var q=20+enc.length;q<20+jp;q++)out[q]=32;var bo=20+jp;d.setUint32(bo,bp,true);d.setUint32(bo+4,0x004e4942,true);out.set(newBin,bo+8);return out.buffer})}
var nativeFetch=window.fetch&&window.fetch.bind(window);if(nativeFetch)window.fetch=function(input,init){var path='';try{path=new URL(typeof input==='string'?input:(input&&input.url)||'',location.href).pathname}catch(e){}if(!/\/models\/cyberfix\.glb$/i.test(path))return nativeFetch(input,init);return nativeFetch(input,init).then(function(r){if(!r.ok)return r;return r.arrayBuffer().then(function(original){diag.status='processing';return rebuild(readGLB(original)).then(function(changed){if(!changed)return new Response(original,{status:r.status,statusText:r.statusText,headers:r.headers});return new Response(changed,{status:r.status,statusText:r.statusText,headers:r.headers})}).catch(function(e){diag.status='rewrite-failed-original-preserved';diag.error=String(e);return new Response(original,{status:r.status,statusText:r.statusText,headers:r.headers})})})})};
})();