(function(){'use strict';
var active=false,videos=new Set(),orig=new WeakMap(),aspect=new WeakMap(),state=new WeakMap(),assignments=[],cursor=0;
var P=[['#05060a','#f6f7fb','#ff4d8d','#7c5cff','#35e0c1'],['#080809','#f7f4ed','#ff8a34','#ef3cff','#55d8ff'],['#04080a','#f2fff9','#2fe4a7','#2c8cff','#d4ff44'],['#090609','#fff6fb','#ff335f','#9d5cff','#ffd166'],['#05070d','#f1f5ff','#47c8ff','#845cff','#ff66c4'],['#070906','#f8ffe8','#c9ff45','#22d3a6','#79a7ff']];
var T=['campaign-film','product-stage','motion-poster','split-case','media-wall','launch-film','app-stage','ambient-brand'];
var V=[
{id:'36518063',label:'neon-night-drive',src:'https://videos.pexels.com/video-files/36518063/15484726_3840_2160_30fps.mp4'},
{id:'29834228',label:'night-city-neon-street',src:'https://videos.pexels.com/video-files/29834228/12812829_2160_3840_24fps.mp4'},
{id:'32119029',label:'urban-nightlife',src:'https://www.pexels.com/download/video/32119029/'},
{id:'32636958',label:'neon-city-nightlife',src:'https://www.pexels.com/download/video/32636958/'},
{id:'10633329',label:'aerial-city-grid',src:'https://www.pexels.com/download/video/10633329/'},
{id:'4687195',label:'city-skyline-drone',src:'https://www.pexels.com/download/video/4687195/'},
{id:'19303831',label:'urban-cityscape-drone',src:'https://www.pexels.com/download/video/19303831/'},
{id:'4046192',label:'downtown-drone',src:'https://www.pexels.com/download/video/4046192/'}];
function sh(a){a=a.slice();for(var i=a.length-1;i;i--){var j=Math.floor(Math.random()*(i+1)),x=a[i];a[i]=a[j];a[j]=x}return a}V=sh(V);
window.__seelaryVideoPool=V.map(function(x){return{id:x.id,label:x.label}});window.__seelaryAssignments=assignments;
window.__seelaryBuildingContent={staticMaterials:[],staticMode:'disabled-safe-no-GLB-rewrite',cityTransport:[],videoAssignments:assignments,mix:'62% cinematic video showcase / 38% campaign art',cardTemplates:T.slice(),videoFit:'cover compositor',creativeDirection:'cinematic-portfolio-showcase'};
function S(v){return v==null?'':String(v)}function mod(a,b){return((a%b)+b)%b}function wave(t,s,p){return .5+.5*Math.sin(t*s+(p||0))}function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function mediaUrl(v){try{return S(v.currentSrc||v.src||v.getAttribute&&v.getAttribute('src')||'')}catch(e){return''}}function project(u){return /\/videos\/[^/]+\.(mp4|webm|mov)(\?|#|$)/i.test(S(u))&&!/\/videos\/loading\.(mp4|webm)(\?|#|$)/i.test(S(u))}function original(v){return orig.get(v)||mediaUrl(v)}
function rr(g,x,y,w,h,r,fill,stroke){r=Math.min(r,w/2,h/2);g.beginPath();g.moveTo(x+r,y);g.arcTo(x+w,y,x+w,y+h,r);g.arcTo(x+w,y+h,x,y+h,r);g.arcTo(x,y+h,x,y,r);g.arcTo(x,y,x+w,y,r);if(fill)g.fill();if(stroke)g.stroke()}
function tx(g,s,x,y,z,w,a,o){g.save();g.globalAlpha=o==null?1:o;g.textAlign=a||'left';g.textBaseline='middle';g.font=(w||600)+' '+Math.max(8,Math.round(z))+'px Arial,Helvetica,sans-serif';g.fillText(s,x,y);g.restore()}
function dot(g,x,y,r,c,o){g.save();g.globalAlpha=o==null?1:o;g.fillStyle=c;g.beginPath();g.arc(x,y,r,0,Math.PI*2);g.fill();g.restore()}
function tile(g,x,y,w,h,p,t,k){var q=g.createLinearGradient(x,y,x+w,y+h);q.addColorStop(0,k%2?p[2]:p[3]);q.addColorStop(1,k%3?p[4]:p[2]);g.globalAlpha=.24+.18*wave(t,.4,k);g.fillStyle=q;rr(g,x,y,w,h,Math.min(w,h)*.07,1,0);g.globalAlpha=1;for(var i=0;i<4;i++){g.fillStyle='rgba(255,255,255,'+(.06+i*.02)+')';rr(g,x+w*.10,y+h*(.18+i*.16),w*(.34+.34*wave(t,.3+i*.05,k+i)),h*.045,h*.014,1,0)}}
function phone(g,x,y,w,h,p,t){g.fillStyle='rgba(255,255,255,.08)';g.strokeStyle='rgba(255,255,255,.28)';g.lineWidth=Math.max(2,h*.008);rr(g,x,y,w,h,h*.055,1,1);g.fillStyle=p[0];rr(g,x+w*.06,y+h*.045,w*.88,h*.91,h*.038,1,0);tile(g,x+w*.10,y+h*.10,w*.80,h*.42,p,t,2);for(var i=0;i<3;i++){g.fillStyle='rgba(255,255,255,.09)';rr(g,x+w*.10,y+h*(.60+i*.09),w*(.48+.20*wave(t,.3+i*.05,i)),h*.038,h*.012,1,0)}g.fillStyle=p[4];rr(g,x+w*.10,y+h*.85,w*.42,h*.065,h*.018,1,0)}
function mark(g,w,h,p,n,title){tx(g,'SEELARY',w*.045,h*.072,h*.034,800,'left',.9);tx(g,String(n+1).padStart(2,'0')+' / '+title,w*.955,h*.072,h*.019,700,'right',.5);g.fillStyle=p[2];g.fillRect(w*.045,h*.108,w*.07,h*.007)}
function card(c,i,t){var g=c.getContext('2d');if(!g)return;var w=c.width,h=c.height,p=P[i%P.length],a;g.fillStyle=p[0];g.fillRect(0,0,w,h);mark(g,w,h,p,i,T[i].replace(/-/g,' '));
if(i===0){tile(g,w*.05,h*.17,w*.62,h*.64,p,t,0);tx(g,'CAMPAIGN',w*.72,h*.31,h*.068,900,'left',.9);tx(g,'IN MOTION',w*.72,h*.40,h*.068,900,'left',.9);tx(g,'FILM / PRODUCT / MEDIA',w*.72,h*.52,h*.021,700,'left',.44);dot(g,w*.84,h*.70,h*.085,p[4],.30)}
else if(i===1){phone(g,w*.08,h*.16,w*.28,h*.69,p,t);tile(g,w*.45,h*.18,w*.46,h*.27,p,t,1);tile(g,w*.45,h*.50,w*.46,h*.25,p,t,2);tx(g,'PRODUCT STAGE',w*.45,h*.84,h*.052,900,'left',.82)}
else if(i===2){var q=mod(t*.15,1);g.save();g.translate(w*.5,h*.5);g.rotate((q-.5)*.05);g.translate(-w*.5,-h*.5);tile(g,w*.16,h*.18,w*.68,h*.62,p,t,3);g.restore();tx(g,'MAKE THE',w*.08,h*.31,h*.082,900,'left',.96);tx(g,'LAUNCH',w*.08,h*.41,h*.082,900,'left',.96);tx(g,'UNMISSABLE',w*.08,h*.51,h*.082,900,'left',.96)}
else if(i===3){tile(g,w*.05,h*.17,w*.55,h*.67,p,t,4);g.fillStyle='rgba(255,255,255,.04)';rr(g,w*.65,h*.20,w*.29,h*.55,h*.025,1,0);['STRATEGY','CREATIVE','MEDIA','GROWTH'].forEach(function(s,k){tx(g,s,w*.69,h*(.30+k*.10),h*.033,800,'left',.55+k*.12)});g.fillStyle=p[4];rr(g,w*.69,h*.69,w*.17,h*.055,h*.018,1,0)}
else if(i===4){var gap=w*.014,cw=(w*.88-gap*2)/3,ch=(h*.66-gap)/2;for(var r=0;r<2;r++)for(var col=0;col<3;col++)tile(g,w*.05+col*(cw+gap),h*.18+r*(ch+gap),cw,ch,p,t,r*3+col);tx(g,'ONE CAMPAIGN / MANY MOMENTS',w*.05,h*.90,h*.028,800,'left',.48)}
else if(i===5){g.fillStyle=p[2];rr(g,w*.06,h*.18,w*.88,h*.23,h*.025,1,0);tx(g,'LAUNCH FILM',w*.10,h*.295,h*.078,900,'left',.96);tile(g,w*.06,h*.48,w*.59,h*.31,p,t,6);g.fillStyle='rgba(255,255,255,.05)';rr(g,w*.70,h*.48,w*.24,h*.31,h*.025,1,0);tx(g,String(Math.round(45+45*wave(t,.28,5)))+'%',w*.82,h*.60,h*.072,900,'center',.92);tx(g,'MOMENTUM',w*.82,h*.70,h*.021,700,'center',.42)}
else if(i===6){phone(g,w*.08,h*.16,w*.27,h*.68,p,t);phone(g,w*.39,h*.21,w*.22,h*.58,p,t+1);phone(g,w*.65,h*.25,w*.18,h*.49,p,t+2);tx(g,'APP / PRODUCT / STORY',w*.08,h*.90,h*.028,800,'left',.48)}
else{var gr=g.createRadialGradient(w*.52,h*.48,0,w*.52,h*.48,w*.58);gr.addColorStop(0,p[3]);gr.addColorStop(1,p[0]);g.globalAlpha=.28;g.fillStyle=gr;g.fillRect(0,0,w,h);g.globalAlpha=1;for(a=0;a<10;a++)dot(g,w*(.15+.07*a),h*(.46+.18*Math.sin(t*.25+a*.72)),h*.028,a%3===0?p[4]:p[2],.55);tx(g,'SEELARY',w*.50,h*.76,h*.095,900,'center',.90);tx(g,'CREATIVE THAT MOVES',w*.50,h*.86,h*.027,700,'center',.48)}}
function capAspect(v){try{if(v.videoWidth&&v.videoHeight)aspect.set(v,clamp(v.videoWidth/v.videoHeight,.45,3.2))}catch(e){}}
function track(v,u){if(!v||v.tagName!=='VIDEO')return v;videos.add(v);if(u&&project(u)&&!orig.has(v))orig.set(v,S(u));capAspect(v);if(!v.__seelaryAspectListener){v.__seelaryAspectListener=true;v.addEventListener('loadedmetadata',function(){capAspect(v)})}window.__seelaryTrackedVideos=videos.size;return v}
var nativeCreateElement=Document.prototype.createElement;Document.prototype.createElement=function(name,options){var el=nativeCreateElement.call(this,name,options);if(S(name).toLowerCase()==='video')track(el);return el};
var mp=window.HTMLMediaElement&&HTMLMediaElement.prototype,srcDesc=mp&&Object.getOwnPropertyDescriptor(mp,'src');if(srcDesc&&srcDesc.set)try{Object.defineProperty(mp,'src',{configurable:true,enumerable:srcDesc.enumerable,get:srcDesc.get,set:function(v){srcDesc.set.call(this,v);if(this.tagName==='VIDEO'){track(this,v);if(active&&project(v)){var self=this;setTimeout(function(){assign(self,false)},0)}}}})}catch(e){console.warn('[Seelary] media tracker unavailable',e)}
function report(){assignments.length=0;videos.forEach(function(v){var z=state.get(v);if(z&&z.kind)assignments.push({original:original(v),kind:z.kind,label:z.label||'',status:z.status||'',template:z.templateName||'',fit:z.fit||'',videoStyle:z.videoStyleName||''})});window.__seelaryAssignments=assignments;window.__seelaryBuildingContent.videoAssignments=assignments}
function schedule(v){var z=state.get(v)||{};if(z.timer)clearTimeout(z.timer);z.timer=setTimeout(function(){assign(v,true)},52000+Math.random()*48000);state.set(v,z)}
function stop(z){if(!z)return;if(z.raf)cancelAnimationFrame(z.raf);if(z.source){try{z.source.pause();z.source.removeAttribute('src');z.source.load()}catch(e){}}z.raf=0;z.source=null}
function size(v){var ar=aspect.get(v)||1.7777778;if(ar>=1)return{w:960,h:Math.max(360,Math.round(960/ar))};return{h:960,w:Math.max(360,Math.round(960*ar))}}
function cover(g,src,x,y,w,h){var sw=src.videoWidth||16,sh=src.videoHeight||9,sar=sw/sh,dar=w/h,sx=0,sy=0,sww=sw,shh=sh;if(sar>dar){sww=sh*dar;sx=(sw-sww)/2}else{shh=sw/dar;sy=(sh-shh)/2}g.drawImage(src,sx,sy,sww,shh,x,y,w,h)}
var VS=['full-bleed','hero-frame','split-product','multi-frame','floating-frame','cinematic-title','product-overlay','poster-reveal'];
function showcase(g,src,w,h,p,t,s){g.fillStyle=p[0];g.fillRect(0,0,w,h);
if(s===0){cover(g,src,0,0,w,h);g.fillStyle='rgba(0,0,0,.18)';g.fillRect(0,h*.88,w,h*.12);tx(g,'SEELARY / CAMPAIGN FILM',w*.04,h*.94,h*.023,800,'left',.70);tx(g,'01',w*.95,h*.94,h*.021,800,'right',.50)}
else if(s===1){var gr=g.createLinearGradient(0,0,w,h);gr.addColorStop(0,p[3]);gr.addColorStop(1,p[0]);g.globalAlpha=.18;g.fillStyle=gr;g.fillRect(0,0,w,h);g.globalAlpha=1;cover(g,src,w*.05,h*.12,w*.68,h*.76);g.strokeStyle='rgba(255,255,255,.20)';g.lineWidth=Math.max(2,h*.004);rr(g,w*.05,h*.12,w*.68,h*.76,h*.015,0,1);tx(g,'SEELARY',w*.78,h*.23,h*.043,900,'left',.90);tx(g,'PROJECT',w*.78,h*.31,h*.028,700,'left',.45);tile(g,w*.78,h*.42,w*.16,h*.20,p,t,1);tx(g,'FILM / MEDIA',w*.78,h*.70,h*.019,700,'left',.40)}
else if(s===2){cover(g,src,0,0,w*.62,h);g.fillStyle=p[0];g.fillRect(w*.62,0,w*.38,h);phone(g,w*.68,h*.18,w*.22,h*.62,p,t);tx(g,'PRODUCT',w*.68,h*.84,h*.034,900,'left',.84);tx(g,'IN MOTION',w*.68,h*.90,h*.025,700,'left',.44)}
else if(s===3){cover(g,src,w*.04,h*.10,w*.52,h*.52);cover(g,src,w*.60,h*.10,w*.36,h*.28);cover(g,src,w*.60,h*.42,w*.36,h*.43);cover(g,src,w*.04,h*.66,w*.52,h*.19);tx(g,'SEELARY / MULTI-SCREEN STUDY',w*.04,h*.92,h*.021,700,'left',.45)}
else if(s===4){var q=wave(t,.33,4),fw=w*(.68+.05*q),fh=h*(.62+.04*q),fx=(w-fw)/2,fy=(h-fh)/2;var gr2=g.createRadialGradient(w*.5,h*.48,0,w*.5,h*.48,w*.6);gr2.addColorStop(0,p[3]);gr2.addColorStop(1,p[0]);g.globalAlpha=.20;g.fillStyle=gr2;g.fillRect(0,0,w,h);g.globalAlpha=1;cover(g,src,fx,fy,fw,fh);g.strokeStyle='rgba(255,255,255,.25)';g.lineWidth=Math.max(2,h*.004);rr(g,fx,fy,fw,fh,h*.018,0,1);dot(g,w*.14,h*.22,h*.055,p[4],.45);dot(g,w*.84,h*.73,h*.075,p[2],.32);tx(g,'SEELARY',w*.06,h*.90,h*.031,800,'left',.70)}
else if(s===5){cover(g,src,0,0,w,h);var sh=g.createLinearGradient(0,0,w,0);sh.addColorStop(0,'rgba(0,0,0,.72)');sh.addColorStop(.52,'rgba(0,0,0,.20)');sh.addColorStop(1,'rgba(0,0,0,.02)');g.fillStyle=sh;g.fillRect(0,0,w,h);tx(g,'MAKE',w*.06,h*.35,h*.10,900,'left',.92);tx(g,'IT MOVE.',w*.06,h*.48,h*.10,900,'left',.92);tx(g,'SEELARY / CAMPAIGN FILM',w*.06,h*.62,h*.022,700,'left',.46);g.fillStyle=p[4];g.fillRect(w*.06,h*.70,w*.16,h*.012)}
else if(s===6){cover(g,src,0,0,w,h);g.fillStyle='rgba(0,0,0,.20)';g.fillRect(w*.64,0,w*.36,h);phone(g,w*.70,h*.17,w*.20,h*.60,p,t);tx(g,'PRODUCT STORY',w*.69,h*.84,h*.025,800,'left',.70);tx(g,'SEELARY',w*.05,h*.92,h*.029,800,'left',.60)}
else{var ph=mod(t*.22,1),cut=w*clamp((ph-.08)/.55,0,1);tile(g,0,0,w,h,p,t,8);if(cut>0)cover(g,src,0,0,cut,h);g.fillStyle='rgba(0,0,0,.20)';g.fillRect(0,h*.84,w,h*.16);tx(g,ph<.58?'CAMPAIGN POSTER':'CAMPAIGN FILM',w*.05,h*.91,h*.029,900,'left',.80);tx(g,'SEELARY',w*.94,h*.91,h*.025,800,'right',.60)}}
function useCard(v,forced){if(!active||!project(original(v)))return;var old=state.get(v)||{};stop(old);var ti=Number.isInteger(forced)?mod(forced,T.length):Math.floor(Math.random()*T.length),sz=size(v),c=nativeCreateElement.call(document,'canvas');c.width=sz.w;c.height=sz.h;if(!c.captureStream){old.kind='card';old.status='captureStream-unavailable';old.templateName=T[ti];state.set(v,old);report();return}var stream=c.captureStream(30),z=old;z.kind='card';z.label='cinematic-campaign';z.template=ti;z.templateName=T[ti];z.status='playing';z.fit='native-canvas';z.start=performance.now();z.canvas=c;state.set(v,z);function frame(now){var cur=state.get(v);if(!cur||cur!==z||cur.kind!=='card')return;card(c,ti,(now-z.start)/1000);z.raf=requestAnimationFrame(frame)}z.raf=requestAnimationFrame(frame);try{capAspect(v);v.pause();v.removeAttribute('src');v.srcObject=stream;v.muted=true;v.loop=true;v.playsInline=true;var p=v.play();if(p&&p.catch)p.catch(function(){});report();schedule(v)}catch(e){z.status='card-error';report()}}
function next(avoid){if(!V.length)return-1;var i=cursor++%V.length;if(V.length>1&&i===avoid)i=cursor++%V.length;return i}
function tryVideo(v,index,attempt){if(!active||!project(original(v))||!srcDesc||!srcDesc.set)return;attempt=attempt||0;if(attempt>=V.length){useCard(v);return}index=mod(index,V.length);var item=V[index],old=state.get(v)||{};stop(old);var sz=size(v),canvas=nativeCreateElement.call(document,'canvas');canvas.width=sz.w;canvas.height=sz.h;if(!canvas.captureStream){useCard(v);return}var g=canvas.getContext('2d');if(!g){useCard(v);return}var src=nativeCreateElement.call(document,'video');src.crossOrigin='anonymous';src.muted=true;src.loop=true;src.playsInline=true;src.preload='auto';var z=old;z.kind='video';z.label=item.label;z.templateName='';z.status='loading';z.videoIndex=index;z.fit='cover';z.source=src;z.canvas=canvas;z.start=performance.now();z.videoStyle=Math.floor(Math.random()*VS.length);z.videoStyleName=VS[z.videoStyle];state.set(v,z);report();var done=false,to=null;function clean(){src.removeEventListener('canplay',ok);src.removeEventListener('error',bad);if(to)clearTimeout(to)}function bad(){if(done)return;done=true;clean();try{src.pause()}catch(e){}tryVideo(v,next(index),attempt+1)}function ok(){if(done)return;done=true;clean();var stream;try{stream=canvas.captureStream(30)}catch(e){useCard(v);return}z.status='playing';state.set(v,z);function frame(now){var cur=state.get(v);if(!cur||cur!==z||cur.kind!=='video')return;try{showcase(g,src,canvas.width,canvas.height,P[index%P.length],(now-z.start)/1000,z.videoStyle)}catch(e){useCard(v);return}z.raf=requestAnimationFrame(frame)}z.raf=requestAnimationFrame(frame);try{capAspect(v);v.pause();v.removeAttribute('src');v.srcObject=stream;v.muted=true;v.loop=true;v.playsInline=true;var play=v.play();if(play&&play.catch)play.catch(function(){});report();schedule(v)}catch(e){useCard(v)}}src.addEventListener('canplay',ok,{once:true});src.addEventListener('error',bad,{once:true});try{srcDesc.set.call(src,item.src);src.load();var p=src.play();if(p&&p.catch)p.catch(function(){});to=setTimeout(bad,12000)}catch(e){bad()}}
function assign(v,force){if(!active||!project(original(v)))return;var z=state.get(v)||{};if(!force&&(z.status==='loading'||z.status==='playing'))return;if(z.timer){clearTimeout(z.timer);z.timer=null}state.set(v,z);if(Math.random()<.62)tryVideo(v,next(z.videoIndex),0);else useCard(v,Number.isInteger(z.template)?z.template+1:undefined)}
function scan(){document.querySelectorAll('video').forEach(function(v){track(v,mediaUrl(v))});var i=0;videos.forEach(function(v){if(project(original(v))&&!state.get(v)){setTimeout(function(){assign(v,false)},i*240+Math.random()*800);i++}});window.__seelaryTrackedVideos=videos.size}
function start(){if(active)return;active=true;window.__seelaryPromoActive=true;scan();new MutationObserver(scan).observe(document.documentElement,{childList:true,subtree:true});setInterval(scan,1500);console.info('[Seelary] cinematic portfolio showcase active; city GLB untouched',window.__seelaryBuildingContent)}
window.addEventListener('load',function(){setTimeout(start,4500)},{once:true});
})();