(function(){'use strict';
var active=false,videos=new Set(),orig=new WeakMap(),state=new WeakMap(),assignments=[],videoCursor=0,textCanvases=new Set(),panelCache=new WeakMap(),seed=1,drawingCard=false;
var CONTENT=/(^|[^a-z])(sign|screen|display|billboard|poster|advert|logo|brand|label|text|font|kanji|japanese|chinese|korean|hologram|monitor|television|tv|led|lcd|neon|banner|lightbox|marquee|storefront|decal|graffiti|placard|promo|media)(\d+)?($|[^a-z])/i;
var STRUCTURE=/(^|[^a-z])(building|road|ground|street|floor|roof|wall|facade|glass|window|concrete|asphalt|metal|pipe|vent|door|frame|rail|stairs|bridge|pole|cable|sidewalk|pavement|curb|column|beam|ceiling|fence)(\d+)?($|[^a-z])/i;
var CARD_COPY=[
  ['SEELARY','GROW YOUR BRAND','CAMPAIGNS BUILT TO MOVE'],
  ['SEELARY','LAUNCH FASTER','FROM IDEA TO ATTENTION'],
  ['SEELARY','TURN CLICKS INTO CUSTOMERS','CREATIVE + PERFORMANCE'],
  ['SEELARY','YOUR NEXT GROWTH ENGINE','CREATE • LAUNCH • GROW'],
  ['SEELARY','MARKETING THAT MOVES','BUILT FOR MODERN BRANDS'],
  ['SEELARY','MAKE ATTENTION COUNT','DESIGN • MEDIA • GROWTH']
];
var PALETTES=[['#05070d','#23d5ff','#8b5cf6','#f7fbff'],['#07050a','#ff3d81','#6ee7ff','#fff7fb'],['#03080a','#42f5b3','#30a7ff','#effff9'],['#08050b','#ff7a18','#ff3dcb','#fff8ef']];
var VIDEO_POOL=[
  {id:'36518063',label:'neon-night-drive',src:'https://videos.pexels.com/video-files/36518063/15484726_3840_2160_30fps.mp4'},
  {id:'29834228',label:'night-city-neon-street',src:'https://videos.pexels.com/video-files/29834228/12812829_2160_3840_24fps.mp4'},
  {id:'32119029',label:'urban-nightlife',src:'https://www.pexels.com/download/video/32119029/'},
  {id:'32636958',label:'neon-city-nightlife',src:'https://www.pexels.com/download/video/32636958/'},
  {id:'10633329',label:'aerial-city-grid',src:'https://www.pexels.com/download/video/10633329/'},
  {id:'4687195',label:'city-skyline-drone',src:'https://www.pexels.com/download/video/4687195/'},
  {id:'19303831',label:'urban-cityscape-drone',src:'https://www.pexels.com/download/video/19303831/'},
  {id:'4046192',label:'downtown-drone',src:'https://www.pexels.com/download/video/4046192/'}
];
function shuffle(a){a=a.slice();for(var i=a.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1)),t=a[i];a[i]=a[j];a[j]=t}return a}
VIDEO_POOL=shuffle(VIDEO_POOL);
window.__seelaryVideoPool=VIDEO_POOL.map(function(x){return{id:x.id,label:x.label}});
window.__seelaryAssignments=assignments;
window.__seelaryBuildingContent={staticMaterials:[],cityTransport:[],textCanvases:0,videoAssignments:assignments,mix:'60% video / 40% promo cards'};
function str(v){return v==null?'':String(v)}
function abs(v){try{return new URL(typeof v==='string'?v:(v&&v.url)||'',location.href)}catch(e){return null}}
function isCity(v){var u=abs(v);return!!(u&&/\/models\/cyberfix\.glb$/i.test(u.pathname))}
function mediaUrl(v){try{return str(v.currentSrc||v.src||v.getAttribute&&v.getAttribute('src')||'')}catch(e){return''}}
function isProjectUrl(u){return /\/videos\/[^/]+\.(mp4|webm|mov)(\?|#|$)/i.test(str(u))&&!/\/videos\/loading\.(mp4|webm)(\?|#|$)/i.test(str(u))}
function original(v){return orig.get(v)||mediaUrl(v)}
function makeCardCanvas(w,h,n,animateTime){
  w=Math.max(64,Math.min(1280,Math.round(w||512)));h=Math.max(32,Math.min(720,Math.round(h||288)));
  var c=document.createElement('canvas');c.width=w;c.height=h;drawCard(c,n,animateTime||0);return c
}
function drawCard(c,n,t){
  var g=c.getContext('2d');if(!g)return;var w=c.width,h=c.height,p=PALETTES[n%PALETTES.length],copy=CARD_COPY[n%CARD_COPY.length];drawingCard=true;
  try{
    g.fillStyle=p[0];g.fillRect(0,0,w,h);
    var grd=g.createLinearGradient(0,0,w,h);grd.addColorStop(0,p[1]);grd.addColorStop(.55,p[2]);grd.addColorStop(1,p[1]);g.globalAlpha=.18;g.fillStyle=grd;g.fillRect(0,0,w,h);g.globalAlpha=1;
    var u=Math.max(2,Math.min(w,h)/28),shift=(t*20)%Math.max(12,u*5);g.strokeStyle='rgba(255,255,255,.14)';g.lineWidth=Math.max(1,u*.18);
    for(var x=-h;x<w+h;x+=u*5){g.beginPath();g.moveTo(x+shift,0);g.lineTo(x-h+shift,h);g.stroke()}
    for(var i=0;i<8;i++){g.globalAlpha=.18+.08*(i%3);g.fillStyle=i%2?p[1]:p[2];var rw=w*(.08+((n+i*7)%23)/100),rh=h*(.035+((n+i*11)%12)/100),rx=((n*71+i*97)%100)/100*w,ry=((n*37+i*61)%100)/100*h;g.fillRect(rx-rw/2,ry-rh/2,rw,rh)}g.globalAlpha=1;
    g.textAlign='center';g.textBaseline='middle';g.fillStyle=p[3];g.font='700 '+Math.max(18,Math.round(h*.18))+'px Arial,Helvetica,sans-serif';g.fillText(copy[0],w/2,h*.34);
    g.font='700 '+Math.max(13,Math.round(h*.105))+'px Arial,Helvetica,sans-serif';g.fillText(copy[1],w/2,h*.55);
    g.font='500 '+Math.max(9,Math.round(h*.055))+'px Arial,Helvetica,sans-serif';g.globalAlpha=.78;g.fillText(copy[2],w/2,h*.71);g.globalAlpha=1;
    g.fillStyle=p[1];g.fillRect(w*.18,h*.81,w*.26,Math.max(2,h*.018));g.fillStyle=p[2];g.fillRect(w*.56,h*.81,w*.26,Math.max(2,h*.018));
  }finally{drawingCard=false}
}
function dataBytes(uri){var b=atob(uri.slice(uri.indexOf(',')+1)),a=new Uint8Array(b.length);for(var i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a}
var STATIC_PANELS=[];try{for(var pc=0;pc<CARD_COPY.length;pc++)STATIC_PANELS.push(dataBytes(makeCardCanvas(512,256,pc,0).toDataURL('image/png')))}catch(e){console.warn('[Seelary] static card generation failed',e)}
function markText(ctx){if(!drawingCard&&ctx&&ctx.canvas){textCanvases.add(ctx.canvas);window.__seelaryBuildingContent.textCanvases=textCanvases.size}}
function patchText(proto){if(!proto)return;['fillText','strokeText'].forEach(function(name){var f=proto[name];if(typeof f!=='function'||f.__seelary)return;function wrap(){markText(this);return f.apply(this,arguments)}wrap.__seelary=true;proto[name]=wrap})}
patchText(window.CanvasRenderingContext2D&&CanvasRenderingContext2D.prototype);patchText(window.OffscreenCanvasRenderingContext2D&&OffscreenCanvasRenderingContext2D.prototype);
function canvasLike(v){return!!(v&&((window.HTMLCanvasElement&&v instanceof HTMLCanvasElement)||(window.OffscreenCanvas&&v instanceof OffscreenCanvas)))}
function replacementFor(c){var p=panelCache.get(c);if(!p){p=makeCardCanvas(c.width||512,c.height||256,seed++,0);panelCache.set(c,p)}return p}
function patchUpload(proto,name){if(!proto||typeof proto[name]!=='function')return;var f=proto[name];if(f.__seelary)return;function wrap(){var a=[].slice.call(arguments);for(var i=a.length-1;i>=0;i--){if(canvasLike(a[i])&&textCanvases.has(a[i])){a[i]=replacementFor(a[i]);break}}return f.apply(this,a)}wrap.__seelary=true;proto[name]=wrap}
['texImage2D','texSubImage2D'].forEach(function(n){patchUpload(window.WebGLRenderingContext&&WebGLRenderingContext.prototype,n);patchUpload(window.WebGL2RenderingContext&&WebGL2RenderingContext.prototype,n)});
function a4(n){return(n+3)&~3}
function parseGlb(buffer){var u=new Uint8Array(buffer),d=new DataView(buffer);if(u.length<20||d.getUint32(0,true)!==0x46546c67||d.getUint32(4,true)!==2)return null;var off=12,ch=[],ji=-1,bi=-1;while(off+8<=u.length){var len=d.getUint32(off,true),type=d.getUint32(off+4,true),end=off+8+len;if(end>u.length)return null;ch.push({type:type,data:u.slice(off+8,end)});if(type===0x4e4f534a&&ji<0)ji=ch.length-1;if(type===0x004e4942&&bi<0)bi=ch.length-1;off=end}if(ji<0)return null;var json=JSON.parse(new TextDecoder().decode(ch[ji].data).replace(/[\0 ]+$/g,''));return{json:json,chunks:ch,jsonIndex:ji,binIndex:bi,bin:bi>=0?ch[bi].data:new Uint8Array(0)}}
function buildGlb(p,bin){var jb=new TextEncoder().encode(JSON.stringify(p.json)),jp=a4(jb.length),jd=new Uint8Array(jp);jd.fill(32);jd.set(jb);p.chunks[p.jsonIndex]={type:0x4e4f534a,data:jd};var bp=a4(bin.length),bd=new Uint8Array(bp);bd.set(bin);if(p.binIndex>=0)p.chunks[p.binIndex]={type:0x004e4942,data:bd};else p.chunks.splice(p.jsonIndex+1,0,{type:0x004e4942,data:bd});var total=12;p.chunks.forEach(function(c){total+=8+c.data.length});var out=new Uint8Array(total),dv=new DataView(out.buffer),off=12;dv.setUint32(0,0x46546c67,true);dv.setUint32(4,2,true);dv.setUint32(8,total,true);p.chunks.forEach(function(c){dv.setUint32(off,c.data.length,true);dv.setUint32(off+4,c.type,true);out.set(c.data,off+8);off+=8+c.data.length});return out.buffer}
function validGlb(b){try{var p=parseGlb(b);if(!p)return false;var n=p.bin.length,views=p.json.bufferViews||[];for(var i=0;i<views.length;i++){var v=views[i]||{},o=v.byteOffset||0,l=v.byteLength||0;if((v.buffer||0)===0&&o+l>n)return false}return true}catch(e){return false}}
function flatPrimitive(j,p){try{var ai=p.attributes&&p.attributes.POSITION,a=j.accessors&&j.accessors[ai];if(!a||!a.min||!a.max)return false;var e=[Math.abs(a.max[0]-a.min[0]),Math.abs(a.max[1]-a.min[1]),Math.abs(a.max[2]-a.min[2])].sort(function(x,y){return x-y});return e[2]>0&&e[0]<=e[2]*.025&&e[1]>=e[2]*.06}catch(e){return false}}
function appendPanels(p){var j=p.json,base=j.buffers&&j.buffers[0]?Math.min(p.bin.length,j.buffers[0].byteLength):p.bin.length,parts=[{offset:0,bytes:p.bin.subarray(0,base)}],cur=base,tex=[];j.bufferViews=j.bufferViews||[];j.images=j.images||[];j.textures=j.textures||[];STATIC_PANELS.forEach(function(b,i){var o=a4(cur);cur=o+b.length;parts.push({offset:o,bytes:b});var vi=j.bufferViews.length;j.bufferViews.push({buffer:0,byteOffset:o,byteLength:b.length,name:'SeelaryPromoCardBuffer'+i});var ii=j.images.length;j.images.push({bufferView:vi,mimeType:'image/png',name:'SeelaryPromoCardImage'+i});var ti=j.textures.length;j.textures.push({source:ii,name:'SeelaryPromoCardTexture'+i});tex.push(ti)});if(!j.buffers||!j.buffers.length)j.buffers=[{byteLength:cur}];else j.buffers[0].byteLength=cur;var bin=new Uint8Array(cur);parts.forEach(function(x){bin.set(x.bytes,x.offset)});return{bin:bin,textures:tex}}
function replaceCityContent(buffer){try{if(!STATIC_PANELS.length)return buffer;var p=parseGlb(buffer);if(!p)return buffer;var j=p.json,mats=j.materials||[],meshes=j.meshes||[],nodes=j.nodes||[],nodeNames=[];nodes.forEach(function(n){if(n&&Number.isInteger(n.mesh))(nodeNames[n.mesh]||(nodeNames[n.mesh]=[])).push(str(n.name))});var uses=mats.map(function(){return[]});meshes.forEach(function(m,mi){var names=[str(m.name)].concat(nodeNames[mi]||[]);(m.primitives||[]).forEach(function(pr){if(pr&&Number.isInteger(pr.material)&&uses[pr.material])uses[pr.material].push({names:names,flat:flatPrimitive(j,pr),uv:!!(pr.attributes&&Number.isInteger(pr.attributes.TEXCOORD_0))})})});var targets=[];mats.forEach(function(m,i){m=m||{};var u=uses[i]||[],names=[str(m.name)];u.forEach(function(x){names=names.concat(x.names)});var joined=names.join(' '),named=CONTENT.test(joined),structural=STRUCTURE.test(joined)&&!named,emissive=!!m.emissiveTexture||!!(m.emissiveFactor&&m.emissiveFactor.some(function(x){return Number(x)>.08})),flat=u.length&&u.every(function(x){return x.flat}),uv=u.some(function(x){return x.uv});if(named||(!structural&&flat&&emissive&&uv))targets.push({index:i,name:str(m.name),why:named?'named-content':'flat-emissive',uv:uv})});if(!targets.length)return buffer;var added=appendPanels(p);targets.forEach(function(t,k){var m=mats[t.index],pb=m.pbrMetallicRoughness||(m.pbrMetallicRoughness={}),ti=added.textures[(k+Math.floor(Math.random()*added.textures.length))%added.textures.length];if(pb.baseColorTexture)pb.baseColorTexture.index=ti;else if(t.uv)pb.baseColorTexture={index:ti};pb.baseColorFactor=[1,1,1,1];if(m.emissiveTexture)m.emissiveTexture.index=ti;else if(t.uv)m.emissiveTexture={index:ti};m.emissiveFactor=[.55,.55,.55]});var out=buildGlb(p,added.bin);if(!validGlb(out)){console.warn('[Seelary] rewritten city failed validation; original kept');return buffer}window.__seelaryBuildingContent.staticMaterials=targets;return out}catch(e){console.warn('[Seelary] city content fallback',e);return buffer}}
function noteTransport(name){var a=window.__seelaryBuildingContent.cityTransport;if(a.indexOf(name)<0)a.push(name)}
if(window.fetch){var previousFetch=window.fetch.bind(window);window.fetch=function(input,init){if(!isCity(input))return previousFetch(input,init);return previousFetch(input,init).then(function(r){if(!r||!r.ok)return r;return r.arrayBuffer().then(function(b){var h=new Headers(r.headers);h.delete('content-length');noteTransport('fetch');return new Response(replaceCityContent(b),{status:r.status,statusText:r.statusText,headers:h})})})}}
if(window.XMLHttpRequest){var xp=XMLHttpRequest.prototype,previousOpen=xp.open,responseDesc=Object.getOwnPropertyDescriptor(xp,'response');xp.open=function(method,u){this.__seelaryCity=isCity(u);this.__seelaryRaw=null;this.__seelaryClean=null;return previousOpen.apply(this,arguments)};if(responseDesc&&responseDesc.get)try{Object.defineProperty(xp,'response',{configurable:true,enumerable:responseDesc.enumerable,get:function(){var r=responseDesc.get.call(this);if(!this.__seelaryCity||!(r instanceof ArrayBuffer))return r;if(this.__seelaryRaw===r&&this.__seelaryClean)return this.__seelaryClean;this.__seelaryRaw=r;this.__seelaryClean=replaceCityContent(r);noteTransport('xhr');return this.__seelaryClean}})}catch(e){console.warn('[Seelary] XHR city-content hook unavailable',e)}}
function track(v,u){if(!v||v.tagName!=='VIDEO')return v;videos.add(v);if(u&&isProjectUrl(u)&&!orig.has(v))orig.set(v,str(u));window.__seelaryTrackedVideos=videos.size;return v}
var nativeCreateElement=Document.prototype.createElement;Document.prototype.createElement=function(name,options){var el=nativeCreateElement.call(this,name,options);if(str(name).toLowerCase()==='video')track(el);return el};
var mediaProto=window.HTMLMediaElement&&HTMLMediaElement.prototype,srcDesc=mediaProto&&Object.getOwnPropertyDescriptor(mediaProto,'src');if(srcDesc&&srcDesc.set)try{Object.defineProperty(mediaProto,'src',{configurable:true,enumerable:srcDesc.enumerable,get:srcDesc.get,set:function(v){srcDesc.set.call(this,v);if(this.tagName==='VIDEO'){track(this,v);if(active&&isProjectUrl(v)){var self=this;setTimeout(function(){assign(self,false)},0)}}}})}catch(e){console.warn('[Seelary] media tracker unavailable',e)}
function report(){assignments.length=0;videos.forEach(function(v){var z=state.get(v);if(z&&z.kind)assignments.push({original:original(v),kind:z.kind,label:z.label||'',status:z.status||''})});window.__seelaryAssignments=assignments;window.__seelaryBuildingContent.videoAssignments=assignments}
function schedule(v){var z=state.get(v)||{};if(z.timer)clearTimeout(z.timer);z.timer=setTimeout(function(){assign(v,true)},55000+Math.random()*40000);state.set(v,z)}
function cardStream(v,cardIndex){var z=state.get(v)||{},card=z.card;if(!card){var c=document.createElement('canvas');c.width=1280;c.height=720;card={canvas:c,stream:null,raf:0,start:performance.now(),index:cardIndex};if(c.captureStream)card.stream=c.captureStream(30);z.card=card;state.set(v,z)}card.index=cardIndex;function frame(now){var current=state.get(v);if(!current||current.kind!=='card'||current.card!==card)return;drawCard(card.canvas,card.index,(now-card.start)/1000);card.raf=requestAnimationFrame(frame)}cancelAnimationFrame(card.raf);card.start=performance.now();card.raf=requestAnimationFrame(frame);return card.stream}
function useCard(v,forcedIndex){if(!active||!isProjectUrl(original(v)))return;var idx=Number.isInteger(forcedIndex)?forcedIndex:Math.floor(Math.random()*CARD_COPY.length),stream=cardStream(v,idx),z=state.get(v)||{};if(!stream){z.kind='card';z.label=CARD_COPY[idx][1];z.status='captureStream-unavailable';state.set(v,z);report();return}try{v.pause();v.removeAttribute('src');v.srcObject=stream;v.muted=true;v.loop=true;v.playsInline=true;z=state.get(v)||{};z.kind='card';z.label=CARD_COPY[idx][1];z.status='playing';z.videoIndex=-1;state.set(v,z);var p=v.play();if(p&&p.catch)p.catch(function(){});report();schedule(v)}catch(e){z.kind='card';z.label=CARD_COPY[idx][1];z.status='error';state.set(v,z);report()}}
function nextVideoIndex(avoid){if(!VIDEO_POOL.length)return-1;var idx=videoCursor++%VIDEO_POOL.length;if(VIDEO_POOL.length>1&&idx===avoid)idx=videoCursor++%VIDEO_POOL.length;return idx}
function tryVideo(v,index,attempt){if(!active||!isProjectUrl(original(v))||!srcDesc||!srcDesc.set)return;attempt=attempt||0;if(attempt>=VIDEO_POOL.length){useCard(v);return}index=(index+VIDEO_POOL.length)%VIDEO_POOL.length;var item=VIDEO_POOL[index],z=state.get(v)||{},done=false,to;z.kind='video';z.label=item.label;z.status='loading';z.videoIndex=index;state.set(v,z);report();function clean(){v.removeEventListener('canplay',ok);v.removeEventListener('error',bad);if(to)clearTimeout(to)}function ok(){if(done)return;done=true;clean();var q=state.get(v)||{};q.kind='video';q.label=item.label;q.status='playing';q.videoIndex=index;state.set(v,q);try{if(isFinite(v.duration)&&v.duration>4)v.currentTime=Math.random()*Math.max(1,v.duration-2)}catch(e){}var p=v.play();if(p&&p.catch)p.catch(function(){});report();schedule(v)}function bad(){if(done)return;done=true;clean();tryVideo(v,nextVideoIndex(index),attempt+1)}v.addEventListener('canplay',ok,{once:true});v.addEventListener('error',bad,{once:true});try{v.pause();v.srcObject=null;v.crossOrigin='anonymous';v.muted=true;v.loop=true;v.playsInline=true;v.preload='auto';srcDesc.set.call(v,item.src);v.load();to=setTimeout(bad,12000)}catch(e){bad()}}
function assign(v,force){if(!active||!isProjectUrl(original(v)))return;var z=state.get(v)||{};if(!force&&(z.status==='loading'||z.status==='playing'))return;if(z.timer){clearTimeout(z.timer);z.timer=null}state.set(v,z);var chooseVideo=Math.random()<.60;if(chooseVideo)tryVideo(v,nextVideoIndex(z.videoIndex),0);else useCard(v)}
function scan(){document.querySelectorAll('video').forEach(function(v){track(v,mediaUrl(v))});var i=0;videos.forEach(function(v){if(isProjectUrl(original(v))&&!state.get(v)){setTimeout(function(){assign(v,false)},i*280+Math.random()*900);i++}});window.__seelaryTrackedVideos=videos.size}
function start(){if(active)return;active=true;window.__seelaryPromoActive=true;scan();new MutationObserver(scan).observe(document.documentElement,{childList:true,subtree:true});setInterval(scan,1500);console.info('[Seelary] city-wide 60/40 video + promo-card system active',window.__seelaryBuildingContent)}
window.addEventListener('load',function(){setTimeout(start,4500)},{once:true});
})();
