(function(){'use strict';
var MEDIA=[
{file:'Abstract_Motion_graphics.webm',label:'abstract-motion',creator:'I-Cheng Lee',license:'CC BY 3.0',source:'https://commons.wikimedia.org/wiki/File:Abstract_Motion_graphics.webm'},
{file:'City_Timelapse_-_Free_video.webm',label:'city-timelapse',creator:'Free Videos',license:'CC BY 3.0',source:'https://commons.wikimedia.org/wiki/File:City_Timelapse_-_Free_video.webm'},
{file:'City_at_night.webm',label:'city-night',creator:'Editor',license:'CC BY 3.0',source:'https://commons.wikimedia.org/wiki/File:City_at_night.webm'},
{file:'City_timelapse_video.webm',label:'city-timelapse-2',creator:'Location Kenya',license:'CC BY 3.0',source:'https://commons.wikimedia.org/wiki/File:City_timelapse_video.webm'},
{file:'City_street_time_lapse.webm',label:'city-street',creator:'Editor',license:'CC BY 3.0',source:'https://commons.wikimedia.org/wiki/File:City_street_time_lapse.webm'},
{file:'Stop_motion_animation.webm',label:'stop-motion',creator:'LanaBanana',license:'CC BY 3.0',source:'https://commons.wikimedia.org/wiki/File:Stop_motion_animation.webm'},
{file:'RainingWebm.webm',label:'rain-motion',creator:'Sergkarman',license:'CC BY 3.0',source:'https://commons.wikimedia.org/wiki/File:RainingWebm.webm'},
{file:'Slow_motion-_drop.webm',label:'slow-motion-drop',creator:'Matthew Frost',license:'CC BY 3.0',source:'https://commons.wikimedia.org/wiki/File:Slow_motion-_drop.webm'}
];
var replacementByOriginal=new Map(),elementAssignments=new WeakMap(),assignments=[],failureCounts=new WeakMap();
function S(v){return v==null?'':String(v)}
function legacy(v){var s=S(v);if(!s)return false;try{var u=new URL(s,location.href),p=u.pathname.toLowerCase();if(/\/videos\/loading\.(mp4|webm)(?:$|[?#])/i.test(p))return false;if(u.hostname==='upload.wikimedia.org'||u.hostname==='commons.wikimedia.org')return false;return /\/videos\/[^/]+\.(mp4|webm|mov)$/i.test(p)||u.origin===location.origin&&/\.(mp4|webm|mov)$/i.test(p)&&!/loading\.(mp4|webm)$/i.test(p)}catch(e){return false}}
function key(v){try{return new URL(S(v),location.href).pathname.toLowerCase()}catch(e){return S(v).toLowerCase()}}
function hash(s){var h=2166136261>>>0;for(var i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function urlFor(item){return 'https://commons.wikimedia.org/wiki/Special:Redirect/file/'+encodeURIComponent(item.file)}
function select(original,offset){var k=key(original),base=hash(k)%MEDIA.length,item=MEDIA[(base+(offset||0))%MEDIA.length];return{original:k,item:item,replacement:urlFor(item)}}
function remember(el,original,sel){replacementByOriginal.set(sel.original,sel);if(el)elementAssignments.set(el,sel);report()}
function report(){assignments.length=0;replacementByOriginal.forEach(function(sel){assignments.push({original:sel.original,replacement:sel.replacement,label:sel.item.label,creator:sel.item.creator,license:sel.item.license,mode:'direct-source-substitution'})});window.__seelaryAssignments=assignments}
window.__seelaryVideoPool=MEDIA.map(function(x){return{label:x.label,creator:x.creator,license:x.license,source:x.source}});
window.__seelaryBuildingContent=Object.assign(window.__seelaryBuildingContent||{},{creativeDirection:'content-only-original-design',videoMode:'direct source substitution',customCompositor:false,customSlides:false,customCanvasVideo:false,originalVideoFallback:false,openMedia:true});
window.__seelaryOriginalVideoBlock={active:true,mode:'direct-source-substitution',originalFallback:false,excluded:['loading.mp4','loading.webm']};
var mediaProto=window.HTMLMediaElement&&HTMLMediaElement.prototype,videoSrc=mediaProto&&Object.getOwnPropertyDescriptor(mediaProto,'src'),sourceProto=window.HTMLSourceElement&&HTMLSourceElement.prototype,sourceSrc=sourceProto&&Object.getOwnPropertyDescriptor(sourceProto,'src'),nativeSetAttribute=Element.prototype.setAttribute,nativeCreateElement=Document.prototype.createElement;
function applyVideo(el,original){var tries=failureCounts.get(el)||0,sel=select(original,tries);remember(el,original,sel);if(el){try{el.crossOrigin='anonymous'}catch(e){}if(!el.__seelaryReplacementError){el.__seelaryReplacementError=true;el.addEventListener('error',function(){var current=elementAssignments.get(el);if(!current)return;var n=(failureCounts.get(el)||0)+1;if(n>=MEDIA.length){window.__seelaryVideoErrors=(window.__seelaryVideoErrors||0)+1;return}failureCounts.set(el,n);var retry=select(current.original,n);remember(el,current.original,retry);try{videoSrc.set.call(el,retry.replacement);if(typeof el.load==='function')el.load()}catch(e){}})}}return sel.replacement}
if(videoSrc&&videoSrc.set)try{Object.defineProperty(mediaProto,'src',{configurable:true,enumerable:videoSrc.enumerable,get:videoSrc.get,set:function(v){if(this.tagName==='VIDEO'&&legacy(v)){videoSrc.set.call(this,applyVideo(this,v));return}videoSrc.set.call(this,v)}})}catch(e){console.warn('[Seelary] direct video substitution unavailable',e)}
if(sourceSrc&&sourceSrc.set)try{Object.defineProperty(sourceProto,'src',{configurable:true,enumerable:sourceSrc.enumerable,get:sourceSrc.get,set:function(v){if(legacy(v)){var parent=this.parentNode&&this.parentNode.tagName==='VIDEO'?this.parentNode:null;sourceSrc.set.call(this,applyVideo(parent,v));return}sourceSrc.set.call(this,v)}})}catch(e){console.warn('[Seelary] direct source substitution unavailable',e)}
Element.prototype.setAttribute=function(name,value){if(String(name).toLowerCase()==='src'&&legacy(value)){if(this.tagName==='VIDEO'){return nativeSetAttribute.call(this,name,applyVideo(this,value))}if(this.tagName==='SOURCE'){var p=this.parentNode&&this.parentNode.tagName==='VIDEO'?this.parentNode:null;return nativeSetAttribute.call(this,name,applyVideo(p,value))}}return nativeSetAttribute.call(this,name,value)};
Document.prototype.createElement=function(name,options){return nativeCreateElement.call(this,name,options)};
function scan(){document.querySelectorAll('video').forEach(function(v){var u='';try{u=v.getAttribute('src')||v.currentSrc||''}catch(e){}if(legacy(u)){var r=applyVideo(v,u);try{videoSrc.set.call(v,r);v.load()}catch(e){}}v.querySelectorAll('source').forEach(function(s){var su='';try{su=s.getAttribute('src')||''}catch(e){}if(legacy(su)){var rr=applyVideo(v,su);try{sourceSrc.set.call(s,rr);v.load()}catch(e){}}})})}
scan();new MutationObserver(scan).observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('load',scan,{once:true});
console.info('[Seelary] content-only media substitution active; original portfolio rendering/layout untouched',window.__seelaryBuildingContent);
})();